### ISSUE TITLE
Segmentation fault while running examples/recurrent-language-model.lua

### ISSUE THREAD

**Issue by nileshkulkarni** [Element-Research/rnn#246]
I am trying to run this example recurrent-language-model.lua. 
When I train it with cuda flag as false it runs perfectly file.
But on trying to run with cuda it gets a segmentation fault on trying to execute this step.

`
local outputs = lm:forward(inputs) 
`

This is the output log from the run. I printed the `inputs` variable.

```
{
   batchSize : 32
   batchsize : 32
   cuda : true
   cutoff : -1
   device : 4
   dropout : 0
   earlystop : 50
   gru : false
   hiddensize : {200}
   id : "test"
   lstm : true
   maxepoch : 10
   maxnormout : -1
   minlr : 1e-05
   momentum : 0.9
   progress : true
   saturate : 400
   savepath : "/home/nilesh/save/rnnlm"
   seqlen : 5
   silent : false
   startlr : 0.05
   trainsize : -1
   uniform : 0.1
   validsize : -1
}
Vocabulary size : 10000
Train set split into 32 sequences of length 29048
Language Model:
nn.Sequential {
  [input -> (1) -> (2) -> (3) -> output]
  (1): nn.LookupTable
  (2): nn.SplitTable
  (3): nn.Sequencer @ nn.Recursor @ nn.Sequential {
    [input -> (1) -> (2) -> (3) -> output]
    (1): nn.FastLSTM(200 -> 200)
    (2): nn.Linear(200 -> 10000)
    (3): nn.LogSoftMax
  }
}

Epoch #1 :
Columns 1 to 13
  238  9013  2523  9120  4935   346  6844   425  8237  1292  7805    46  9049
  808  1817  9120  9013    45  6143  5503    49  6447  9060    45    46  1417
  951  9839  3054  7956    49  4771  6058  3757    45  6143  3569  7576  9013
 1326   903  6189  9011    45  6168  4156  1884  5134  4266  9583  2160  5564
 1477  5364  9346  9013  9583   425  5424    44  9013  8772  6844   477    45

Columns 14 to 26
 3826  9934    45  3973  2542  4547  7481  4471  6203    49  9013  3670  3291
 5111    44   425    44  9013  6874  9011  9013  4404     2  6962  7408  9120
  103  9030  5268  1292  3344  4246    46  7844  9030    46  6081  1795   874
 9120   556  9120  2059  6143  9706  6492  1230   556   988  9911  6186    46
 9453    45  8456   414  9013  7481  4082   610    46  1274  6186  3460  9120

Columns 27 to 32
 3040  9120   988  1817  3395  6143
 4471  1955  4471  6158  9780  7962
 9013  9013  9013  9780   759  3911
 8201  4436  9754  5861  4471  3773
 9534  6143  3062   730  9013  4266
[torch.IntTensor of size 5x32]

Segmentation fault (core dumped)

```

Any possible issues that might cause this.
Also, I checked that I had all the dependencies. 
cunn, cunnx, cutroch

Thanks,
Nilesh

**Comment by nicholas-leonard** [comment]
@nileshkulkarni I had a similar problem with a different script which was solved by importing cunn before allocating any large memory chunks. I just updated the script with this change : https://github.com/Element-Research/rnn/commit/9dbcb6889796c7730db780f9bad6c456322cbbb5 . Update rnn and let me know if it helps. Otherwise, I wasn't able to reproduce your error on my end.

**Comment by nileshkulkarni** [comment]
@nicholas-leonard  I tried to run with your fix but I still get the same Seg fault.
Any other way I could show you the problem? Probably the output of core file?, but I don't how to get a detailed log of the core.

Any ideas/ suggestions would be great.

Thanks

**Comment by nileshkulkarni** [comment]
@nicholas-leonard Solved the problem. 

I was using lua instead of luajit to run the examples.

luajit examples/recurrent-language-model.lua  works perfectly fine with cuda.

This issue can be closed now.

**Comment by nicholas-leonard** [comment]
@nileshkulkarni Ok sounds good.
